{
  "defaultProject": "klemmBld",
  "projects": [
	{
	  "name": "klemmBld",
	  "debug": true,
	  "outputPath": "bin",
	  "sources": [
		"Source/*.cpp"
	  ],
	  "includes": [
		"json/include"
	  ],
	  "optimization": "fast"
	}
  ]
}