{
  "defaultTarget": "klemmBld",
  "targets": [
	{
	  "name": "klemmBld",
	  "debug": true,
	  "outputPath": "bin",
	  "sources": [
		"Source/*.cpp"
	  ],
	  "includes": [
		"json/include"
	  ],
	  "optimization": "fastest"
	}
  ]
}